[package]
name = "hers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
enum_dispatch = "0.3.13"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
thiserror = "1.0.63"
